name: GraphQL Configuration
type: module
description: 'Expose configuration entities and objects in GraphQL.'
package: GraphQL
configure: graphql_configuration.config_page
core: 8.x
dependencies:
  - graphql:graphql_core
